### PR TITLE
Add basic command line interface.

### PR DESCRIPTION
**Pull request by garetht**
This pull request adds a command line interface to `json-schema-resolve-allof` that allows standard input to be piped into the command.

### CODE REVIEW

**Comment by loganvolkers** [comment]
Thanks for the pull request @garetht 

Can you tell me about the design decisions here? Did you evaluate other libraries and approaches before settling on stdin?

In the past I've used [Commander](https://www.npmjs.com/package/commander) to build out CLI layers.

**Comment by garetht** [comment]
I considered using Commander for a while but it seemed unnecessarily heavy for a CLI that does only one thing. I can move it to Commander if you'd like and maybe add a help flag and the option to take a file.

**Comment by loganvolkers** [comment]
Sounds reasonable to me. Looks like `get-stdin` is pretty lightweight and arguably Commander would be a bigger task and a separate package.

**Comment by loganvolkers** [comment]
Released in `v1.2.0`

**Pull request merged**
